//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocio.Entities.ModelPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARRERA()
        {
            this.PLAN = new HashSet<PLAN>();
        }
    
        public int CAR_ID { get; set; }
        public string CAR_CODIGO { get; set; }
        public string CAR_NOMBRE { get; set; }
        public Nullable<int> FAC_ID { get; set; }
    
        public virtual FACULTAD FACULTAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN> PLAN { get; set; }
    }
}
