//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocio.Entities.ModelPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLEGIO
    {
        public int COL_ID { get; set; }
        public string COL_NOMBRE { get; set; }
        public string COL_CIUDAD { get; set; }
        public Nullable<int> TPC_ID { get; set; }
        public string COL_EMAIL_PERSONAL { get; set; }
        public Nullable<int> COL_ANIO_GRADO { get; set; }
        public Nullable<decimal> COL_PENSION { get; set; }
        public Nullable<decimal> COL_PUNTAJE { get; set; }
        public Nullable<int> MEN_ID { get; set; }
        public Nullable<int> EST_ID { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual MENSION MENSION { get; set; }
        public virtual TIPO_COLEGIO TIPO_COLEGIO { get; set; }
    }
}
