//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocio.Entities.ModelPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTUDIANTE()
        {
            this.COLEGIO = new HashSet<COLEGIO>();
        }
    
        public int EST_ID { get; set; }
        public string EST_CEDULA { get; set; }
        public string EST_NOMBRES { get; set; }
        public string EST_APELLIDOS { get; set; }
        public Nullable<System.DateTime> EST_FNACIMIENTO { get; set; }
        public string EST_SEXO { get; set; }
        public Nullable<int> PLA_ID { get; set; }
        public string EST_EMAIL { get; set; }
        public string EST_TEL_DOMICILIO { get; set; }
        public string EST_TEL_CELULAR { get; set; }
        public string EST_DIRECCION { get; set; }
        public string EST_OBSERVACION { get; set; }
        public Nullable<int> AFI_ID { get; set; }
        public Nullable<int> ASO_ID { get; set; }
        public Nullable<int> MOT_ID { get; set; }
    
        public virtual AFICION AFICION { get; set; }
        public virtual ASOCIACION ASOCIACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLEGIO> COLEGIO { get; set; }
        public virtual MOTIVACION MOTIVACION { get; set; }
        public virtual PLAN PLAN { get; set; }
    }
}
