//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocio.Entities.ModelPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int LOG_ID { get; set; }
        public string LOG_MODULO { get; set; }
        public string LOG_USUARIO { get; set; }
        public string LOG_TRANSACCION { get; set; }
        public Nullable<System.DateTime> LOG_FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> LOG_FECHA_EDICION { get; set; }
        public Nullable<System.DateTime> LOG_FECHA_ELIMINACION { get; set; }
        public string LOG_DIRECCIONIP { get; set; }
    }
}
