//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocio.Entities.ModelPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERIA()
        {
            this.PLAN_MATERIA = new HashSet<PLAN_MATERIA>();
        }
    
        public int MAT_ID { get; set; }
        public string MAT_CODIGO { get; set; }
        public string MAT_NOMBRE { get; set; }
        public Nullable<int> MAT_NIVEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN_MATERIA> PLAN_MATERIA { get; set; }
    }
}
