//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaNegocio.Entities.ModelPs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_MATERIA
    {
        public int PLM_ID { get; set; }
        public Nullable<int> PLA_ID { get; set; }
        public Nullable<int> MAT_ID { get; set; }
    
        public virtual MATERIA MATERIA { get; set; }
        public virtual PLAN PLAN { get; set; }
    }
}
